blank_issues_enabled: false
contact_links:
  - name: 🤔 Ask a Question
    url: https://github.com/steveschmidt-philips/skills-expand-your-team-with-copilot/discussions
    about: Ask questions about using the High School Management System
  - name: 📖 Documentation
    url: https://github.com/steveschmidt-philips/skills-expand-your-team-with-copilot/blob/main/README.md
    about: Read the system documentation and setup guide